### ISSUE TITLE
sometimes everyone go to steve skin

### ISSUE THREAD

**Issue by rjworks** [PresentKim/PersonaSkin#3]
sometimes everyone goes to steve skin, not sure why it does that

**Comment by alvin0319** [comment]
Make sure to disable the Settings -> Profile -> Allow only trusted skins setting.

**Comment by rjworks** [comment]
> Make sure to disable the Settings -> Profile -> Allow only trusted skins setting.

That's always been my settings but sometimes in game everyone turns to Steve

**Comment by PresentKim** [comment]
If this plugin doesn't work properly, you should see a one-color skin(Not working), or server crashed (Error).
What appears to be simply Steve doesn't seem to be a problem of this plugin.
