### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rjworks** [PresentKim/PersonaSkin#8]
01:07:39] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to kim\present\personaskin\libs\kim\present\converter\png\PngConverter::kim\present\personaskin\libs\kim\present\converter\png\{closure}() must be of the type int, array given, called in phar://C:/Users/arjay/Documents/Personal projects/Minecraft/plugins/PersonaSkin_dev-14.phar/src/kim/present/personaskin/libs/kim/present/converter/png/libs/kim/present/lib/arrayutils/ArrayUtils.php on line 571" (EXCEPTION) in "plugins/PersonaSkin_dev-14.phar/src/kim/present/personaskin/libs/kim/present/converter/png/PngConverter" at line 74

**Comment by KadTheHunter** [comment]
I'm getting this as well, on the official release.

**Comment by rjworks** [comment]
now it just doesnt work at all

**Comment by KadTheHunter** [comment]
Some of my players have been getting this error randomly even without a CC skin. Just going to remove the plugin at this point.

**Comment by MacaylaMarvelous81** [comment]
I think it is caused [here](https://github.com/PresentKim/png-converter/blob/d4d94f444a34f587be8bacd0743700ae70eb154a/src/kim/present/converter/png/PngConverter.php#L74) in the forEach

**Comment by pjprijs** [comment]
Same issue here :(

`[Server thread/CRITICAL]: TypeError: "Argument 1 passed to kim\present\personaskin\libs\kim\present\converter\png\PngConverter::kim\present\personaskin\libs\kim\present\converter\png\{closure}() must be of the type int, array given, called in phar:///Users/****/Documents/MCPE/plugins/PersonaSkin.phar/src/kim/present/personaskin/libs/kim/present/converter/png/libs/kim/present/lib/arrayutils/ArrayUtils.php on line 571" (EXCEPTION) in "plugins/PersonaSkin.phar/src/kim/present/personaskin/libs/kim/present/converter/png/PngConverter" at line 74`

**Comment by KadTheHunter** [comment]
> Same issue here :(
> 
> `[Server thread/CRITICAL]: TypeError: "Argument 1 passed to kim\present\personaskin\libs\kim\present\converter\png\PngConverter::kim\present\personaskin\libs\kim\present\converter\png\{closure}() must be of the type int, array given, called in phar:///Users/****/Documents/MCPE/plugins/PersonaSkin.phar/src/kim/present/personaskin/libs/kim/present/converter/png/libs/kim/present/lib/arrayutils/ArrayUtils.php on line 571" (EXCEPTION) in "plugins/PersonaSkin.phar/src/kim/present/personaskin/libs/kim/present/converter/png/PngConverter" at line 74`

I've just given up on getting this fixed.

**Comment by KadTheHunter** [comment]
Wow, nice to see it's fixed.
Completely forgot this even existed tbh xD

**Comment by PresentKim** [comment]
> 

I forgot too
